### ISSUE TITLE
Drupal 11 and Postgres 16

### ISSUE THREAD

**Issue by DuaelFr** [lando/drupal#146]
I can't track why it's happening but I am unable to start a project using `postgres` 16 with the `drupal11` recipe.
When using the `drupal10` recipe, it's working expectedly.

My versions:
```
 @lando/cli             v3.23.14         
 @lando/core            v3.23.14         
 @lando/drupal          v1.9.2  
 ```
 
My lando file:
```
name: d11pg16
recipe: drupal11
config:
  webroot: .
  database: postgres
```

The result:
```
$ lando rebuild -y
ERROR ==> drupal-postgres version 16 is not supported
```

Side note: specifying `postgres:16` gives the same result.
