### ISSUE TITLE
Composer broken by latest release of lando/php

### ISSUE THREAD

**Issue by NickDickinsonWilde** [lando/drupal#153]
When rebuilding containers that used to work, composer is no longer available.

example config:
```
recipe: drupal11
config:
  composer: 2-latest
  via: nginx
  database: mariadb:10.11
  xdebug: false
  php: 8.4
  webroot: web
```
(also happening with drupal10 recipe for another developer). 

This is both before *and* after running lando update and installing latest (1.7.0) lando/php - I'm assuming that is not fixing it due to nesting of dependencies.
