### ISSUE TITLE
How to setup chromedriver to test javascript files

### ISSUE THREAD

**Issue by smustgrave** [lando/drupal#27]

**Comment by almunnings** [comment]
Just kinda stumbled on this.

You might have some luck with the below, changing `SIMPLETEST_BASE_URL`

```yml
services:
  chrome:
    type: compose
    app_mount: false
    services:
      image: drupalci/webdriver-chromedriver:production
      security_opt:
        - seccomp:unconfined
      command: chromedriver --verbose --allowed-ips= --allowed-origins=*
      platform: linux/amd64

tooling:
    phpunit:
    env:
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless","--no-sandbox"]}}, "http://chrome:9515"]'
      SIMPLETEST_DB: 'sqlite://localhost//tmp/.sqlite'
      SIMPLETEST_BASE_URL: 'http://YOURLANDOSITE.lndo.site/'
      SYMFONY_DEPRECATIONS_HELPER: 'disabled'
    cmd:
      - appserver: /app/vendor/bin/phpunit -c /app/web/core/ --stop-on-failure /app/web/modules/custom


```

2 years late?! Hopefully it helps someone.
