### ISSUE TITLE
Problem with Drupal10 recepite default composer version

### ISSUE THREAD

**Issue by cdt-team** [lando/drupal#75]
Hello for work correctly with Drupal 10 we should use at least Composer version 2.3.6 or higher, as suggest in the [documentation](https://www.drupal.org/project/drupal/releases/10.0.0#:~:text=for%20more%20information.-,Composer%20requirements,receive%20warnings%20on%20older%20versions.)

I try to install Drupal 10 as suggested in the lando recepit documentation, and if I install the **dev** repo composer version is set to 2.4.4, https://docs.lando.dev/drupal/getting-started.html:
`lando composer create-project drupal/recommended-project:10.0.x-dev@dev tmp && cp -r tmp/. . && rm -rf tmp`

but if i try to install the latest Drupal 10 version the composer version is 2.2.x, and I not find a correct way to override the composer version inside the .lando.yml
`lando composer create-project drupal/recommended-project:10.x tmp && cp -r tmp/. . && rm -rf tmp`

Here is my lando.yml file

```
name: d10-test
recipe: drupal10
excludes:
  - vendor
  - node_modules
  - modules/contrib
services:
  cache:
    type: redis
    persist: true
config:
  php: 8.2
  composer_version: 2-latest
  via: nginx
  webroot: web
tooling:
  redis-cli:
    service: cache
```
